export const mainPages = [
  {
    id: crypto.randomUUID(),
    title: "Калькулятор GPA",
    icon: <i className="bi bi-calculator"></i>,
    description: "Быстро и удобно рассчитайте свой GPA",
    file: "GpaCalc",
    path: "gpa",
  },
  {
    id: crypto.randomUUID(),
    title: "Конвертер оценок",
    icon: <i className="bi bi-arrow-left-right"></i>,
    description: "Конвертируйте баллы в буквенную оценку",
    file: "Converter",
    path: "converter",
  },
  {
    id: crypto.randomUUID(),
    title: "Делитель на команды",
    icon: <i className="bi bi-people-fill"></i>,
    description:
      "Автоматически разделите группу людей на нужное число подгрупп",
    file: "TeamDiv",
    path: "teamdiv",
  },
  {
    id: crypto.randomUUID(),
    title: "Генератор QR",
    icon: <i className="bi bi-qr-code-scan"></i>,
    description: "Легко создайте QR-код для ссылки или текста",
    file: "QrGen",
    path: "qrgen",
  },
  {
    id: crypto.randomUUID(),
    title: "Счётчик слов",
    icon: <i className="bi bi-text-wrap"></i>,
    description: "Простая программа для подсчёта слов в вставленном тексте",
    file: "WordCounter",
    path: "wordcounter",
  },
  {
    id: crypto.randomUUID(),
    title: "Время до конца пары",
    icon: <i className="bi bi-alarm-fill"></i>,
    description: "Это задумано для показа на экране во время экзамена",
    file: "Timer",
    path: "timer",
  },
  {
    id: crypto.randomUUID(),
    title: "Аффирмации",
    icon: <i className="bi bi-person-heart"></i>,
    description: "Небольшие мотивирующие цитаты для поднятия духа",
    file: "Affirmations",
    path: "affirmations",
  },
  {
    id: crypto.randomUUID(),
    title: "Генератор объяснительных",
    icon: <i className="bi bi-file-earmark-font-fill"></i>,
    description: "ИИ для создания формального текста из простого объяснения",
    file: "ExcuseGen",
    path: "excusegen",
  },
  {
    id: crypto.randomUUID(),
    title: "Генератор писем",
    icon: <i className="bi bi-envelope-at-fill"></i>,
    description:
      "ИИ для создания формальных электронных писем из простого сообщения",
    file: "EmailGen",
    path: "emailgen",
  },
];
